server:
  port: 8090

netty:
  port: 9999
  boss-count: 5
  worker-count: 5
  keep-alive: true
  backlog: 100


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&serverTimezone=Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:


logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: debug